cors:
  enabled: true

endpoints:
  api1:
    base-url: http://localhost:8080/api/

feign:
  client.config.default:
    loggerLevel: FULL

logging:
  config: classpath:logs/log4j2-spring.dev.xml

server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: template
    password: template
  jpa:
    properties:
      hibernate:
        default_schema: template
        format_sql: true
        type: TRACE
  flyway:
    enabled: true
    clean-disabled: true
    schemas: TEMPLATE
    locations: classpath:db/migration/common,classpath:db/migration/others
